language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - node_modules
before_install:
- set -e
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- npm install
- sudo apt-get install python3-pip
- python3 --version
- pip3 --version
- sudo -H pip3 install --upgrade setuptools pip wheel
- sudo -H pip3 install --upgrade tox twine
script:
  - npm run lint
  - npm run lint-test
  - npm test
  - tox -e qa
after_success: npm run coverage
